## Importing The Libaries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

%matplotlib inline

In [2]:
## loading the data
df = pd.read_csv("C:/Users/ammanana/Desktop/technocolabs/prosperLoanData.csv")

In [3]:
## checking starting 5 rows
df.head()

,ListingKey,ListingNumber,ListingCreationDate,CreditGrade,Term,LoanStatus,ClosedDate,BorrowerAPR,BorrowerRate,LenderYield,...,LP_ServiceFees,LP_CollectionFees,LP_GrossPrincipalLoss,LP_NetPrincipalLoss,LP_NonPrincipalRecoverypayments,PercentFunded,Recommendations,InvestmentFromFriendsCount,InvestmentFromFriendsAmount,Investors
0,1021339766868145413AB3B,193129,2007-08-26 19:09:29.263000000,C,36,Completed,2009-08-14 00:00:00,0.16516,0.1580,0.1380,...,-133.18,0.0,0.0,0.0,0.0,1.0,0,0,0.0,258
1,10273602499503308B223C1,1209647,2014-02-27 08:28:07.900000000,NaN,36,Current,NaN,0.12016,0.0920,0.0820,...,0.00,0.0,0.0,0.0,0.0,1.0,0,0,0.0,1
2,0EE9337825851032864889A,81716,2007-01-05 15:00:47.090000000,HR,36,Completed,2009-12-17 00:00:00,0.28269,0.2750,0.2400,...,-24.20,0.0,0.0,0.0,0.0,1.0,0,0,0.0,41
3,0EF5356002482715299901A,658116,2012-10-22 11:02:35.010000000,NaN,36,Current,NaN,0.12528,0.0974,0.0874,...,-108.01,0.0,0.0,0.0,0.0,1.0,0,0,0.0,158
4,0F023589499656230C5E3E2,909464,2013-09-14 18:38:39.097000000,NaN,36,Current,NaN,0.24614,0.2085,0.1985,...,-60.27,0.0,0.0,0.0,0.0,1.0,0,0,0.0,20

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 113937 entries, 0 to 113936
Data columns (total 81 columns):
 #   Column                               Non-Null Count   Dtype
---  ------                               --------------   -----
 0   ListingKey                           113937 non-null  object
 1   ListingNumber                        113937 non-null  int64
 2   ListingCreationDate                  113937 non-null  object
 3   CreditGrade                          28953 non-null   object
 4   Term                                 113937 non-null  int64
 5   LoanStatus                           113937 non-null  object
 6   ClosedDate                           55089 non-null   object
 7   BorrowerAPR                          113912 non-null  float64
 8   BorrowerRate                         113937 non-null  float64
 9   LenderYield                          113937 non-null  float64
 10  EstimatedEffectiveYield              84853 non-null   float64
 11  EstimatedLoss                        84853 non-null   float64
 12  EstimatedReturn                      84853 non-null   float64
 13  ProsperRating (numeric)              84853 non-null   float64
 14  ProsperRating (Alpha)                84853 non-null   object
 15  ProsperScore                         84853 non-null   float64
 16  ListingCategory (numeric)            113937 non-null  int64
 17  BorrowerState                        108422 non-null  object
 18  Occupation                           110349 non-null  object
 19  EmploymentStatus                     111682 non-null  object
 20  EmploymentStatusDuration             106312 non-null  float64
 21  IsBorrowerHomeowner                  113937 non-null  bool
 22  CurrentlyInGroup                     113937 non-null  bool
 23  GroupKey                             13341 non-null   object
 24  DateCreditPulled                     113937 non-null  object
 25  CreditScoreRangeLower                113346 non-null  float64
 26  CreditScoreRangeUpper                113346 non-null  float64
 27  FirstRecordedCreditLine              113240 non-null  object
 28  CurrentCreditLines                   106333 non-null  float64
 29  OpenCreditLines                      106333 non-null  float64
 30  TotalCreditLinespast7years           113240 non-null  float64
 31  OpenRevolvingAccounts                113937 non-null  int64
 32  OpenRevolvingMonthlyPayment          113937 non-null  float64
 33  InquiriesLast6Months                 113240 non-null  float64
 34  TotalInquiries                       112778 non-null  float64
 35  CurrentDelinquencies                 113240 non-null  float64
 36  AmountDelinquent                     106315 non-null  float64
 37  DelinquenciesLast7Years              112947 non-null  float64
 38  PublicRecordsLast10Years             113240 non-null  float64
 39  PublicRecordsLast12Months            106333 non-null  float64
 40  RevolvingCreditBalance               106333 non-null  float64
 41  BankcardUtilization                  106333 non-null  float64
 42  AvailableBankcardCredit              106393 non-null  float64
 43  TotalTrades                          106393 non-null  float64
 44  TradesNeverDelinquent (percentage)   106393 non-null  float64
 45  TradesOpenedLast6Months              106393 non-null  float64
 46  DebtToIncomeRatio                    105383 non-null  float64
 47  IncomeRange                          113937 non-null  object
 48  IncomeVerifiable                     113937 non-null  bool
 49  StatedMonthlyIncome                  113937 non-null  float64
 50  LoanKey                              113937 non-null  object
 51  TotalProsperLoans                    22085 non-null   float64
 52  TotalProsperPaymentsBilled           22085 non-null   float64
 53  OnTimeProsperPayments                22085 non-null   float64
 54  ProsperPaymentsLessThanOneMonthLate  22085 non-null   float64
 55  ProsperPaymentsOneMonthPlusLate      22085 non-null   float64
 56  ProsperPrincipalBorrowed             22085 non-null   float64
 57  ProsperPrincipalOutstanding          22085 non-null   float64
 58  ScorexChangeAtTimeOfListing          18928 non-null   float64
 59  LoanCurrentDaysDelinquent            113937 non-null  int64
 60  LoanFirstDefaultedCycleNumber        16952 non-null   float64
 61  LoanMonthsSinceOrigination           113937 non-null  int64
 62  LoanNumber                           113937 non-null  int64
 63  LoanOriginalAmount                   113937 non-null  int64
 64  LoanOriginationDate                  113937 non-null  object
 65  LoanOriginationQuarter               113937 non-null  object
 66  MemberKey                            113937 non-null  object
 67  MonthlyLoanPayment                   113937 non-null  float64
 68  LP_CustomerPayments                  113937 non-null  float64
 69  LP_CustomerPrincipalPayments         113937 non-null  float64
 70  LP_InterestandFees                   113937 non-null  float64
 71  LP_ServiceFees                       113937 non-null  float64
 72  LP_CollectionFees                    113937 non-null  float64
 73  LP_GrossPrincipalLoss                113937 non-null  float64
 74  LP_NetPrincipalLoss                  113937 non-null  float64
 75  LP_NonPrincipalRecoverypayments      113937 non-null  float64
 76  PercentFunded                        113937 non-null  float64
 77  Recommendations                      113937 non-null  int64
 78  InvestmentFromFriendsCount           113937 non-null  int64
 79  InvestmentFromFriendsAmount          113937 non-null  float64
 80  Investors                            113937 non-null  int64
dtypes: bool(3), float64(50), int64(11), object(17)
memory usage: 68.1+ MB

In [5]:
## shape of data

df.shape

(113937, 81)

In [6]:
# Duplicates data entry in loan data
df.duplicated().sum()

0

In [7]:
#checking the captalization
df['LoanStatus'].value_counts(dropna=False)

Current                   56576
Completed                 38074
Chargedoff                11992
Defaulted                  5018
Past Due (1-15 days)        806
Past Due (31-60 days)       363
Past Due (61-90 days)       313
Past Due (91-120 days)      304
Past Due (16-30 days)       265
FinalPaymentInProgress      205
Past Due (>120 days)         16
Cancelled                     5
Name: LoanStatus, dtype: int64

## DATA LABELING

In [8]:
## creating target variable by status object in closeddate having nullvalue has 1 and for value we update it has 0.

df["Status"] = df["ClosedDate"].apply(lambda x: 1 if pd.isnull(x) else 0)

In [9]:
### after closeddate we will select loancurrentdaydelinquent the value with grater than 180 as 1 and less than 180 as 0.
df["Status"] = df["LoanCurrentDaysDelinquent"].apply(lambda x: 1 if x > 180 else 0)

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 113937 entries, 0 to 113936
Data columns (total 82 columns):
 #   Column                               Non-Null Count   Dtype
---  ------                               --------------   -----
 0   ListingKey                           113937 non-null  object
 1   ListingNumber                        113937 non-null  int64
 2   ListingCreationDate                  113937 non-null  object
 3   CreditGrade                          28953 non-null   object
 4   Term                                 113937 non-null  int64
 5   LoanStatus                           113937 non-null  object
 6   ClosedDate                           55089 non-null   object
 7   BorrowerAPR                          113912 non-null  float64
 8   BorrowerRate                         113937 non-null  float64
 9   LenderYield                          113937 non-null  float64
 10  EstimatedEffectiveYield              84853 non-null   float64
 11  EstimatedLoss                        84853 non-null   float64
 12  EstimatedReturn                      84853 non-null   float64
 13  ProsperRating (numeric)              84853 non-null   float64
 14  ProsperRating (Alpha)                84853 non-null   object
 15  ProsperScore                         84853 non-null   float64
 16  ListingCategory (numeric)            113937 non-null  int64
 17  BorrowerState                        108422 non-null  object
 18  Occupation                           110349 non-null  object
 19  EmploymentStatus                     111682 non-null  object
 20  EmploymentStatusDuration             106312 non-null  float64
 21  IsBorrowerHomeowner                  113937 non-null  bool
 22  CurrentlyInGroup                     113937 non-null  bool
 23  GroupKey                             13341 non-null   object
 24  DateCreditPulled                     113937 non-null  object
 25  CreditScoreRangeLower                113346 non-null  float64
 26  CreditScoreRangeUpper                113346 non-null  float64
 27  FirstRecordedCreditLine              113240 non-null  object
 28  CurrentCreditLines                   106333 non-null  float64
 29  OpenCreditLines                      106333 non-null  float64
 30  TotalCreditLinespast7years           113240 non-null  float64
 31  OpenRevolvingAccounts                113937 non-null  int64
 32  OpenRevolvingMonthlyPayment          113937 non-null  float64
 33  InquiriesLast6Months                 113240 non-null  float64
 34  TotalInquiries                       112778 non-null  float64
 35  CurrentDelinquencies                 113240 non-null  float64
 36  AmountDelinquent                     106315 non-null  float64
 37  DelinquenciesLast7Years              112947 non-null  float64
 38  PublicRecordsLast10Years             113240 non-null  float64
 39  PublicRecordsLast12Months            106333 non-null  float64
 40  RevolvingCreditBalance               106333 non-null  float64
 41  BankcardUtilization                  106333 non-null  float64
 42  AvailableBankcardCredit              106393 non-null  float64
 43  TotalTrades                          106393 non-null  float64
 44  TradesNeverDelinquent (percentage)   106393 non-null  float64
 45  TradesOpenedLast6Months              106393 non-null  float64
 46  DebtToIncomeRatio                    105383 non-null  float64
 47  IncomeRange                          113937 non-null  object
 48  IncomeVerifiable                     113937 non-null  bool
 49  StatedMonthlyIncome                  113937 non-null  float64
 50  LoanKey                              113937 non-null  object
 51  TotalProsperLoans                    22085 non-null   float64
 52  TotalProsperPaymentsBilled           22085 non-null   float64
 53  OnTimeProsperPayments                22085 non-null   float64
 54  ProsperPaymentsLessThanOneMonthLate  22085 non-null   float64
 55  ProsperPaymentsOneMonthPlusLate      22085 non-null   float64
 56  ProsperPrincipalBorrowed             22085 non-null   float64
 57  ProsperPrincipalOutstanding          22085 non-null   float64
 58  ScorexChangeAtTimeOfListing          18928 non-null   float64
 59  LoanCurrentDaysDelinquent            113937 non-null  int64
 60  LoanFirstDefaultedCycleNumber        16952 non-null   float64
 61  LoanMonthsSinceOrigination           113937 non-null  int64
 62  LoanNumber                           113937 non-null  int64
 63  LoanOriginalAmount                   113937 non-null  int64
 64  LoanOriginationDate                  113937 non-null  object
 65  LoanOriginationQuarter               113937 non-null  object
 66  MemberKey                            113937 non-null  object
 67  MonthlyLoanPayment                   113937 non-null  float64
 68  LP_CustomerPayments                  113937 non-null  float64
 69  LP_CustomerPrincipalPayments         113937 non-null  float64
 70  LP_InterestandFees                   113937 non-null  float64
 71  LP_ServiceFees                       113937 non-null  float64
 72  LP_CollectionFees                    113937 non-null  float64
 73  LP_GrossPrincipalLoss                113937 non-null  float64
 74  LP_NetPrincipalLoss                  113937 non-null  float64
 75  LP_NonPrincipalRecoverypayments      113937 non-null  float64
 76  PercentFunded                        113937 non-null  float64
 77  Recommendations                      113937 non-null  int64
 78  InvestmentFromFriendsCount           113937 non-null  int64
 79  InvestmentFromFriendsAmount          113937 non-null  float64
 80  Investors                            113937 non-null  int64
 81  Status                               113937 non-null  int64
dtypes: bool(3), float64(50), int64(12), object(17)
memory usage: 69.0+ MB

In [11]:
import pandas as pd

# Assuming you have a DataFrame named 'df' with columns 'CreditScoreRangeLower' and 'CreditScoreRangeUpper'
# Replace these values with your actual DataFrame and column names

df['CreditScore'] = df.apply(lambda row: (row['CreditScoreRangeLower'] + row['CreditScoreRangeUpper']) / 2, axis=1)

In [12]:
## dropping uncessary columns
df.drop(columns=['ListingKey','ListingNumber','EmploymentStatusDuration','DateCreditPulled','LoanKey','ScorexChangeAtTimeOfListing','LoanFirstDefaultedCycleNumber',
                 'LoanMonthsSinceOrigination','LoanNumber','MemberKey','LP_InterestandFees','LP_ServiceFees','LP_CollectionFees','LP_GrossPrincipalLoss','LP_NetPrincipalLoss',
                 'LP_NonPrincipalRecoverypayments','CreditScoreRangeLower','CreditScoreRangeUpper','GroupKey'],axis=1,inplace=True)

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 113937 entries, 0 to 113936
Data columns (total 64 columns):
 #   Column                               Non-Null Count   Dtype
---  ------                               --------------   -----
 0   ListingCreationDate                  113937 non-null  object
 1   CreditGrade                          28953 non-null   object
 2   Term                                 113937 non-null  int64
 3   LoanStatus                           113937 non-null  object
 4   ClosedDate                           55089 non-null   object
 5   BorrowerAPR                          113912 non-null  float64
 6   BorrowerRate                         113937 non-null  float64
 7   LenderYield                          113937 non-null  float64
 8   EstimatedEffectiveYield              84853 non-null   float64
 9   EstimatedLoss                        84853 non-null   float64
 10  EstimatedReturn                      84853 non-null   float64
 11  ProsperRating (numeric)              84853 non-null   float64
 12  ProsperRating (Alpha)                84853 non-null   object
 13  ProsperScore                         84853 non-null   float64
 14  ListingCategory (numeric)            113937 non-null  int64
 15  BorrowerState                        108422 non-null  object
 16  Occupation                           110349 non-null  object
 17  EmploymentStatus                     111682 non-null  object
 18  IsBorrowerHomeowner                  113937 non-null  bool
 19  CurrentlyInGroup                     113937 non-null  bool
 20  FirstRecordedCreditLine              113240 non-null  object
 21  CurrentCreditLines                   106333 non-null  float64
 22  OpenCreditLines                      106333 non-null  float64
 23  TotalCreditLinespast7years           113240 non-null  float64
 24  OpenRevolvingAccounts                113937 non-null  int64
 25  OpenRevolvingMonthlyPayment          113937 non-null  float64
 26  InquiriesLast6Months                 113240 non-null  float64
 27  TotalInquiries                       112778 non-null  float64
 28  CurrentDelinquencies                 113240 non-null  float64
 29  AmountDelinquent                     106315 non-null  float64
 30  DelinquenciesLast7Years              112947 non-null  float64
 31  PublicRecordsLast10Years             113240 non-null  float64
 32  PublicRecordsLast12Months            106333 non-null  float64
 33  RevolvingCreditBalance               106333 non-null  float64
 34  BankcardUtilization                  106333 non-null  float64
 35  AvailableBankcardCredit              106393 non-null  float64
 36  TotalTrades                          106393 non-null  float64
 37  TradesNeverDelinquent (percentage)   106393 non-null  float64
 38  TradesOpenedLast6Months              106393 non-null  float64
 39  DebtToIncomeRatio                    105383 non-null  float64
 40  IncomeRange                          113937 non-null  object
 41  IncomeVerifiable                     113937 non-null  bool
 42  StatedMonthlyIncome                  113937 non-null  float64
 43  TotalProsperLoans                    22085 non-null   float64
 44  TotalProsperPaymentsBilled           22085 non-null   float64
 45  OnTimeProsperPayments                22085 non-null   float64
 46  ProsperPaymentsLessThanOneMonthLate  22085 non-null   float64
 47  ProsperPaymentsOneMonthPlusLate      22085 non-null   float64
 48  ProsperPrincipalBorrowed             22085 non-null   float64
 49  ProsperPrincipalOutstanding          22085 non-null   float64
 50  LoanCurrentDaysDelinquent            113937 non-null  int64
 51  LoanOriginalAmount                   113937 non-null  int64
 52  LoanOriginationDate                  113937 non-null  object
 53  LoanOriginationQuarter               113937 non-null  object
 54  MonthlyLoanPayment                   113937 non-null  float64
 55  LP_CustomerPayments                  113937 non-null  float64
 56  LP_CustomerPrincipalPayments         113937 non-null  float64
 57  PercentFunded                        113937 non-null  float64
 58  Recommendations                      113937 non-null  int64
 59  InvestmentFromFriendsCount           113937 non-null  int64
 60  InvestmentFromFriendsAmount          113937 non-null  float64
 61  Investors                            113937 non-null  int64
 62  Status                               113937 non-null  int64
 63  CreditScore                          113346 non-null  float64
dtypes: bool(3), float64(40), int64(9), object(12)
memory usage: 53.4+ MB

### Handling Missing Values

In [14]:
null_count = {}
for columns in df:
    null_count[columns] = df[columns].isnull().sum()

In [15]:
null_count

{'ListingCreationDate': 0,
 'CreditGrade': 84984,
 'Term': 0,
 'LoanStatus': 0,
 'ClosedDate': 58848,
 'BorrowerAPR': 25,
 'BorrowerRate': 0,
 'LenderYield': 0,
 'EstimatedEffectiveYield': 29084,
 'EstimatedLoss': 29084,
 'EstimatedReturn': 29084,
 'ProsperRating (numeric)': 29084,
 'ProsperRating (Alpha)': 29084,
 'ProsperScore': 29084,
 'ListingCategory (numeric)': 0,
 'BorrowerState': 5515,
 'Occupation': 3588,
 'EmploymentStatus': 2255,
 'IsBorrowerHomeowner': 0,
 'CurrentlyInGroup': 0,
 'FirstRecordedCreditLine': 697,
 'CurrentCreditLines': 7604,
 'OpenCreditLines': 7604,
 'TotalCreditLinespast7years': 697,
 'OpenRevolvingAccounts': 0,
 'OpenRevolvingMonthlyPayment': 0,
 'InquiriesLast6Months': 697,
 'TotalInquiries': 1159,
 'CurrentDelinquencies': 697,
 'AmountDelinquent': 7622,
 'DelinquenciesLast7Years': 990,
 'PublicRecordsLast10Years': 697,
 'PublicRecordsLast12Months': 7604,
 'RevolvingCreditBalance': 7604,
 'BankcardUtilization': 7604,
 'AvailableBankcardCredit': 7544,
 'TotalTrades': 7544,
 'TradesNeverDelinquent (percentage)': 7544,
 'TradesOpenedLast6Months': 7544,
 'DebtToIncomeRatio': 8554,
 'IncomeRange': 0,
 'IncomeVerifiable': 0,
 'StatedMonthlyIncome': 0,
 'TotalProsperLoans': 91852,
 'TotalProsperPaymentsBilled': 91852,
 'OnTimeProsperPayments': 91852,
 'ProsperPaymentsLessThanOneMonthLate': 91852,
 'ProsperPaymentsOneMonthPlusLate': 91852,
 'ProsperPrincipalBorrowed': 91852,
 'ProsperPrincipalOutstanding': 91852,
 'LoanCurrentDaysDelinquent': 0,
 'LoanOriginalAmount': 0,
 'LoanOriginationDate': 0,
 'LoanOriginationQuarter': 0,
 'MonthlyLoanPayment': 0,
 'LP_CustomerPayments': 0,
 'LP_CustomerPrincipalPayments': 0,
 'PercentFunded': 0,
 'Recommendations': 0,
 'InvestmentFromFriendsCount': 0,
 'InvestmentFromFriendsAmount': 0,
 'Investors': 0,
 'Status': 0,
 'CreditScore': 591}

## Categorical Data

In [16]:
categorical_data = df.select_dtypes("object")
categorical_data.head()

,ListingCreationDate,CreditGrade,LoanStatus,ClosedDate,ProsperRating (Alpha),BorrowerState,Occupation,EmploymentStatus,FirstRecordedCreditLine,IncomeRange,LoanOriginationDate,LoanOriginationQuarter
0,2007-08-26 19:09:29.263000000,C,Completed,2009-08-14 00:00:00,NaN,CO,Other,Self-employed,2001-10-11 00:00:00,"$25,000-49,999",2007-09-12 00:00:00,Q3 2007
1,2014-02-27 08:28:07.900000000,NaN,Current,NaN,A,CO,Professional,Employed,1996-03-18 00:00:00,"$50,000-74,999",2014-03-03 00:00:00,Q1 2014
2,2007-01-05 15:00:47.090000000,HR,Completed,2009-12-17 00:00:00,NaN,GA,Other,Not available,2002-07-27 00:00:00,Not displayed,2007-01-17 00:00:00,Q1 2007
3,2012-10-22 11:02:35.010000000,NaN,Current,NaN,A,GA,Skilled Labor,Employed,1983-02-28 00:00:00,"$25,000-49,999",2012-11-01 00:00:00,Q4 2012
4,2013-09-14 18:38:39.097000000,NaN,Current,NaN,D,MN,Executive,Employed,2004-02-20 00:00:00,"$100,000+",2013-09-20 00:00:00,Q3 2013

In [17]:
categorical_data.isnull().sum()

ListingCreationDate            0
CreditGrade                84984
LoanStatus                     0
ClosedDate                 58848
ProsperRating (Alpha)      29084
BorrowerState               5515
Occupation                  3588
EmploymentStatus            2255
FirstRecordedCreditLine      697
IncomeRange                    0
LoanOriginationDate            0
LoanOriginationQuarter         0
dtype: int64

In [18]:
categorical_data['CreditGrade'].fillna("not available",inplace=True)
categorical_data['ProsperRating (Alpha)'].fillna("not available",inplace=True)
categorical_data['BorrowerState'] = categorical_data['BorrowerState'].fillna(categorical_data['BorrowerState'].mode().iloc[0])
categorical_data['Occupation'] = categorical_data['Occupation'].fillna(categorical_data['Occupation'].mode().iloc[0])
categorical_data['EmploymentStatus'] = categorical_data['EmploymentStatus'].fillna(categorical_data['EmploymentStatus'].mode().iloc[0])
categorical_data['FirstRecordedCreditLine'] = categorical_data['FirstRecordedCreditLine'].fillna(categorical_data['FirstRecordedCreditLine'].mode().iloc[0])

In [19]:
categorical_data.isnull().sum()

ListingCreationDate            0
CreditGrade                    0
LoanStatus                     0
ClosedDate                 58848
ProsperRating (Alpha)          0
BorrowerState                  0
Occupation                     0
EmploymentStatus               0
FirstRecordedCreditLine        0
IncomeRange                    0
LoanOriginationDate            0
LoanOriginationQuarter         0
dtype: int64

## Numerical Data

In [20]:
numerical_data_int = df.select_dtypes(["int"])
numerical_data_int.head()

,Term,ListingCategory (numeric),OpenRevolvingAccounts,LoanCurrentDaysDelinquent,LoanOriginalAmount,Recommendations,InvestmentFromFriendsCount,Investors,Status
0,36,0,1,0,9425,0,0,258,0
1,36,2,13,0,10000,0,0,1,0
2,36,0,0,0,3001,0,0,41,0
3,36,16,7,0,10000,0,0,158,0
4,36,2,6,0,15000,0,0,20,0

In [21]:
numerical_data_int.isnull().sum()

Term                          0
ListingCategory (numeric)     0
OpenRevolvingAccounts         0
LoanCurrentDaysDelinquent     0
LoanOriginalAmount            0
Recommendations               0
InvestmentFromFriendsCount    0
Investors                     0
Status                        0
dtype: int64

In [22]:
numerical_data_float = df.select_dtypes(["float"])
numerical_data_float.head()

,BorrowerAPR,BorrowerRate,LenderYield,EstimatedEffectiveYield,EstimatedLoss,EstimatedReturn,ProsperRating (numeric),ProsperScore,CurrentCreditLines,OpenCreditLines,...,ProsperPaymentsLessThanOneMonthLate,ProsperPaymentsOneMonthPlusLate,ProsperPrincipalBorrowed,ProsperPrincipalOutstanding,MonthlyLoanPayment,LP_CustomerPayments,LP_CustomerPrincipalPayments,PercentFunded,InvestmentFromFriendsAmount,CreditScore
0,0.16516,0.1580,0.1380,NaN,NaN,NaN,NaN,NaN,5.0,4.0,...,NaN,NaN,NaN,NaN,330.43,11396.14,9425.00,1.0,0.0,649.5
1,0.12016,0.0920,0.0820,0.07960,0.0249,0.05470,6.0,7.0,14.0,14.0,...,NaN,NaN,NaN,NaN,318.93,0.00,0.00,1.0,0.0,689.5
2,0.28269,0.2750,0.2400,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,123.32,4186.63,3001.00,1.0,0.0,489.5
3,0.12528,0.0974,0.0874,0.08490,0.0249,0.06000,6.0,9.0,5.0,5.0,...,NaN,NaN,NaN,NaN,321.45,5143.20,4091.09,1.0,0.0,809.5
4,0.24614,0.2085,0.1985,0.18316,0.0925,0.09066,3.0,4.0,19.0,19.0,...,0.0,0.0,11000.0,9947.9,563.97,2819.85,1563.22,1.0,0.0,689.5

In [23]:
numerical_data_float.isnull().sum()

BorrowerAPR                               25
BorrowerRate                               0
LenderYield                                0
EstimatedEffectiveYield                29084
EstimatedLoss                          29084
EstimatedReturn                        29084
ProsperRating (numeric)                29084
ProsperScore                           29084
CurrentCreditLines                      7604
OpenCreditLines                         7604
TotalCreditLinespast7years               697
OpenRevolvingMonthlyPayment                0
InquiriesLast6Months                     697
TotalInquiries                          1159
CurrentDelinquencies                     697
AmountDelinquent                        7622
DelinquenciesLast7Years                  990
PublicRecordsLast10Years                 697
PublicRecordsLast12Months               7604
RevolvingCreditBalance                  7604
BankcardUtilization                     7604
AvailableBankcardCredit                 7544
TotalTrades                             7544
TradesNeverDelinquent (percentage)      7544
TradesOpenedLast6Months                 7544
DebtToIncomeRatio                       8554
StatedMonthlyIncome                        0
TotalProsperLoans                      91852
TotalProsperPaymentsBilled             91852
OnTimeProsperPayments                  91852
ProsperPaymentsLessThanOneMonthLate    91852
ProsperPaymentsOneMonthPlusLate        91852
ProsperPrincipalBorrowed               91852
ProsperPrincipalOutstanding            91852
MonthlyLoanPayment                         0
LP_CustomerPayments                        0
LP_CustomerPrincipalPayments               0
PercentFunded                              0
InvestmentFromFriendsAmount                0
CreditScore                              591
dtype: int64

In [25]:
numerical_data_float['ProsperRating (numeric)'].fillna(0.0,inplace=True)
numerical_data_float['ProsperScore'].fillna(0.0,inplace=True)
numerical_data_float['CurrentCreditLines'].fillna(0.0,inplace=True)
numerical_data_float['OpenCreditLines'].fillna(0.0,inplace=True)
numerical_data_float['TotalCreditLinespast7years'].fillna(0.0,inplace=True)
numerical_data_float['InquiriesLast6Months'].fillna(0.0,inplace=True)
numerical_data_float['TotalInquiries'].fillna(0.0,inplace=True)
numerical_data_float['CurrentDelinquencies'].fillna(0.0,inplace=True)
numerical_data_float['AmountDelinquent'].fillna(0.0,inplace=True)
numerical_data_float['DelinquenciesLast7Years'].fillna(0.0,inplace=True)
numerical_data_float['PublicRecordsLast10Years'].fillna(0.0,inplace=True)
numerical_data_float['PublicRecordsLast12Months'].fillna(0.0,inplace=True)
numerical_data_float['RevolvingCreditBalance'].fillna(0.0,inplace=True)
numerical_data_float['BankcardUtilization'].fillna(0.0,inplace=True)
numerical_data_float['AvailableBankcardCredit'].fillna(0.0,inplace=True)
numerical_data_float['TotalTrades'].fillna(0.0,inplace=True)
numerical_data_float['TradesOpenedLast6Months'].fillna(0.0,inplace=True)
numerical_data_float['DebtToIncomeRatio'].fillna(0.0,inplace=True)

In [26]:
numerical_data_float.isnull().sum()

BorrowerAPR                               25
BorrowerRate                               0
LenderYield                                0
EstimatedEffectiveYield                29084
EstimatedLoss                          29084
EstimatedReturn                        29084
ProsperRating (numeric)                    0
ProsperScore                               0
CurrentCreditLines                         0
OpenCreditLines                            0
TotalCreditLinespast7years                 0
OpenRevolvingMonthlyPayment                0
InquiriesLast6Months                       0
TotalInquiries                             0
CurrentDelinquencies                       0
AmountDelinquent                           0
DelinquenciesLast7Years                    0
PublicRecordsLast10Years                   0
PublicRecordsLast12Months                  0
RevolvingCreditBalance                     0
BankcardUtilization                        0
AvailableBankcardCredit                    0
TotalTrades                                0
TradesNeverDelinquent (percentage)      7544
TradesOpenedLast6Months                    0
DebtToIncomeRatio                          0
StatedMonthlyIncome                        0
TotalProsperLoans                      91852
TotalProsperPaymentsBilled             91852
OnTimeProsperPayments                  91852
ProsperPaymentsLessThanOneMonthLate    91852
ProsperPaymentsOneMonthPlusLate        91852
ProsperPrincipalBorrowed               91852
ProsperPrincipalOutstanding            91852
MonthlyLoanPayment                         0
LP_CustomerPayments                        0
LP_CustomerPrincipalPayments               0
PercentFunded                              0
InvestmentFromFriendsAmount                0
CreditScore                              591
dtype: int64

In [27]:
numerical_data_float = numerical_data_float.fillna(numerical_data_float.mean())
numerical_data_float.head()

,BorrowerAPR,BorrowerRate,LenderYield,EstimatedEffectiveYield,EstimatedLoss,EstimatedReturn,ProsperRating (numeric),ProsperScore,CurrentCreditLines,OpenCreditLines,...,ProsperPaymentsLessThanOneMonthLate,ProsperPaymentsOneMonthPlusLate,ProsperPrincipalBorrowed,ProsperPrincipalOutstanding,MonthlyLoanPayment,LP_CustomerPayments,LP_CustomerPrincipalPayments,PercentFunded,InvestmentFromFriendsAmount,CreditScore
0,0.16516,0.1580,0.1380,0.168661,0.080306,0.096068,0.0,0.0,5.0,4.0,...,0.613629,0.04854,8472.311961,2930.313906,330.43,11396.14,9425.00,1.0,0.0,649.5
1,0.12016,0.0920,0.0820,0.079600,0.024900,0.054700,6.0,7.0,14.0,14.0,...,0.613629,0.04854,8472.311961,2930.313906,318.93,0.00,0.00,1.0,0.0,689.5
2,0.28269,0.2750,0.2400,0.168661,0.080306,0.096068,0.0,0.0,0.0,0.0,...,0.613629,0.04854,8472.311961,2930.313906,123.32,4186.63,3001.00,1.0,0.0,489.5
3,0.12528,0.0974,0.0874,0.084900,0.024900,0.060000,6.0,9.0,5.0,5.0,...,0.613629,0.04854,8472.311961,2930.313906,321.45,5143.20,4091.09,1.0,0.0,809.5
4,0.24614,0.2085,0.1985,0.183160,0.092500,0.090660,3.0,4.0,19.0,19.0,...,0.000000,0.00000,11000.000000,9947.900000,563.97,2819.85,1563.22,1.0,0.0,689.5

In [28]:
numerical_data_float.isnull().sum()

BorrowerAPR                            0
BorrowerRate                           0
LenderYield                            0
EstimatedEffectiveYield                0
EstimatedLoss                          0
EstimatedReturn                        0
ProsperRating (numeric)                0
ProsperScore                           0
CurrentCreditLines                     0
OpenCreditLines                        0
TotalCreditLinespast7years             0
OpenRevolvingMonthlyPayment            0
InquiriesLast6Months                   0
TotalInquiries                         0
CurrentDelinquencies                   0
AmountDelinquent                       0
DelinquenciesLast7Years                0
PublicRecordsLast10Years               0
PublicRecordsLast12Months              0
RevolvingCreditBalance                 0
BankcardUtilization                    0
AvailableBankcardCredit                0
TotalTrades                            0
TradesNeverDelinquent (percentage)     0
TradesOpenedLast6Months                0
DebtToIncomeRatio                      0
StatedMonthlyIncome                    0
TotalProsperLoans                      0
TotalProsperPaymentsBilled             0
OnTimeProsperPayments                  0
ProsperPaymentsLessThanOneMonthLate    0
ProsperPaymentsOneMonthPlusLate        0
ProsperPrincipalBorrowed               0
ProsperPrincipalOutstanding            0
MonthlyLoanPayment                     0
LP_CustomerPayments                    0
LP_CustomerPrincipalPayments           0
PercentFunded                          0
InvestmentFromFriendsAmount            0
CreditScore                            0
dtype: int64

## Bool Data

In [30]:
bool_data = df.select_dtypes(["bool"])
bool_data.head()

   IsBorrowerHomeowner  CurrentlyInGroup  IncomeVerifiable
0                 True              True              True
1                False             False              True
2                False              True              True
3                 True             False              True
4                 True             False              True

In [31]:
##concatnating the data

data = pd.concat([categorical_data,numerical_data_int,numerical_data_float,bool_data],axis=1)

In [32]:
data.head()

,ListingCreationDate,CreditGrade,LoanStatus,ClosedDate,ProsperRating (Alpha),BorrowerState,Occupation,EmploymentStatus,FirstRecordedCreditLine,IncomeRange,...,ProsperPrincipalOutstanding,MonthlyLoanPayment,LP_CustomerPayments,LP_CustomerPrincipalPayments,PercentFunded,InvestmentFromFriendsAmount,CreditScore,IsBorrowerHomeowner,CurrentlyInGroup,IncomeVerifiable
0,2007-08-26 19:09:29.263000000,C,Completed,2009-08-14 00:00:00,not available,CO,Other,Self-employed,2001-10-11 00:00:00,"$25,000-49,999",...,2930.313906,330.43,11396.14,9425.00,1.0,0.0,649.5,True,True,True
1,2014-02-27 08:28:07.900000000,not available,Current,NaN,A,CO,Professional,Employed,1996-03-18 00:00:00,"$50,000-74,999",...,2930.313906,318.93,0.00,0.00,1.0,0.0,689.5,False,False,True
2,2007-01-05 15:00:47.090000000,HR,Completed,2009-12-17 00:00:00,not available,GA,Other,Not available,2002-07-27 00:00:00,Not displayed,...,2930.313906,123.32,4186.63,3001.00,1.0,0.0,489.5,False,True,True
3,2012-10-22 11:02:35.010000000,not available,Current,NaN,A,GA,Skilled Labor,Employed,1983-02-28 00:00:00,"$25,000-49,999",...,2930.313906,321.45,5143.20,4091.09,1.0,0.0,809.5,True,False,True
4,2013-09-14 18:38:39.097000000,not available,Current,NaN,D,MN,Executive,Employed,2004-02-20 00:00:00,"$100,000+",...,9947.900000,563.97,2819.85,1563.22,1.0,0.0,689.5,True,False,True

In [33]:
count_data = {}
for columns in data:
    count_data[columns] = data[columns].isnull().sum()

print(count_data)

{'ListingCreationDate': 0, 'CreditGrade': 0, 'LoanStatus': 0, 'ClosedDate': 58848, 'ProsperRating (Alpha)': 0, 'BorrowerState': 0, 'Occupation': 0, 'EmploymentStatus': 0, 'FirstRecordedCreditLine': 0, 'IncomeRange': 0, 'LoanOriginationDate': 0, 'LoanOriginationQuarter': 0, 'Term': 0, 'ListingCategory (numeric)': 0, 'OpenRevolvingAccounts': 0, 'LoanCurrentDaysDelinquent': 0, 'LoanOriginalAmount': 0, 'Recommendations': 0, 'InvestmentFromFriendsCount': 0, 'Investors': 0, 'Status': 0, 'BorrowerAPR': 0, 'BorrowerRate': 0, 'LenderYield': 0, 'EstimatedEffectiveYield': 0, 'EstimatedLoss': 0, 'EstimatedReturn': 0, 'ProsperRating (numeric)': 0, 'ProsperScore': 0, 'CurrentCreditLines': 0, 'OpenCreditLines': 0, 'TotalCreditLinespast7years': 0, 'OpenRevolvingMonthlyPayment': 0, 'InquiriesLast6Months': 0, 'TotalInquiries': 0, 'CurrentDelinquencies': 0, 'AmountDelinquent': 0, 'DelinquenciesLast7Years': 0, 'PublicRecordsLast10Years': 0, 'PublicRecordsLast12Months': 0, 'RevolvingCreditBalance': 0, 'BankcardUtilization': 0, 'AvailableBankcardCredit': 0, 'TotalTrades': 0, 'TradesNeverDelinquent (percentage)': 0, 'TradesOpenedLast6Months': 0, 'DebtToIncomeRatio': 0, 'StatedMonthlyIncome': 0, 'TotalProsperLoans': 0, 'TotalProsperPaymentsBilled': 0, 'OnTimeProsperPayments': 0, 'ProsperPaymentsLessThanOneMonthLate': 0, 'ProsperPaymentsOneMonthPlusLate': 0, 'ProsperPrincipalBorrowed': 0, 'ProsperPrincipalOutstanding': 0, 'MonthlyLoanPayment': 0, 'LP_CustomerPayments': 0, 'LP_CustomerPrincipalPayments': 0, 'PercentFunded': 0, 'InvestmentFromFriendsAmount': 0, 'CreditScore': 0, 'IsBorrowerHomeowner': 0, 'CurrentlyInGroup': 0, 'IncomeVerifiable': 0}

In [34]:
data['ClosedDate'] = data['ClosedDate'].fillna(data['ClosedDate'].mode().iloc[0])

In [35]:
count_data = {}
for columns in data:
    count_data[columns] = data[columns].isnull().sum()

print(count_data)

{'ListingCreationDate': 0, 'CreditGrade': 0, 'LoanStatus': 0, 'ClosedDate': 0, 'ProsperRating (Alpha)': 0, 'BorrowerState': 0, 'Occupation': 0, 'EmploymentStatus': 0, 'FirstRecordedCreditLine': 0, 'IncomeRange': 0, 'LoanOriginationDate': 0, 'LoanOriginationQuarter': 0, 'Term': 0, 'ListingCategory (numeric)': 0, 'OpenRevolvingAccounts': 0, 'LoanCurrentDaysDelinquent': 0, 'LoanOriginalAmount': 0, 'Recommendations': 0, 'InvestmentFromFriendsCount': 0, 'Investors': 0, 'Status': 0, 'BorrowerAPR': 0, 'BorrowerRate': 0, 'LenderYield': 0, 'EstimatedEffectiveYield': 0, 'EstimatedLoss': 0, 'EstimatedReturn': 0, 'ProsperRating (numeric)': 0, 'ProsperScore': 0, 'CurrentCreditLines': 0, 'OpenCreditLines': 0, 'TotalCreditLinespast7years': 0, 'OpenRevolvingMonthlyPayment': 0, 'InquiriesLast6Months': 0, 'TotalInquiries': 0, 'CurrentDelinquencies': 0, 'AmountDelinquent': 0, 'DelinquenciesLast7Years': 0, 'PublicRecordsLast10Years': 0, 'PublicRecordsLast12Months': 0, 'RevolvingCreditBalance': 0, 'BankcardUtilization': 0, 'AvailableBankcardCredit': 0, 'TotalTrades': 0, 'TradesNeverDelinquent (percentage)': 0, 'TradesOpenedLast6Months': 0, 'DebtToIncomeRatio': 0, 'StatedMonthlyIncome': 0, 'TotalProsperLoans': 0, 'TotalProsperPaymentsBilled': 0, 'OnTimeProsperPayments': 0, 'ProsperPaymentsLessThanOneMonthLate': 0, 'ProsperPaymentsOneMonthPlusLate': 0, 'ProsperPrincipalBorrowed': 0, 'ProsperPrincipalOutstanding': 0, 'MonthlyLoanPayment': 0, 'LP_CustomerPayments': 0, 'LP_CustomerPrincipalPayments': 0, 'PercentFunded': 0, 'InvestmentFromFriendsAmount': 0, 'CreditScore': 0, 'IsBorrowerHomeowner': 0, 'CurrentlyInGroup': 0, 'IncomeVerifiable': 0}

In [36]:
data.to_csv('prosper_loan_data.csv')